on:
  push:

jobs:
  build:
    runs-on: 'macos-latest'

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: 3.10

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile main.py

    - uses: actions/upload-artifact@v2
      with:
        path: mac-dist/